config/routes.rb
Rails.application.routes.draw do
  resources :concepts
  devise_for :teachers
  devise_for :students, :controllers => { :registrations => "registrations" }
  devise_for :users

   root 'courses#index'
   put 'courses/:id/register', to: 'courses#register'
   get '/learned_courses/:lc_id/concepts/:id/learn', to: 'concepts#learn'
   get '/courses/:id/students', to: 'courses#students'
   get 'courses/:course_id/students/:id', to: 'courses#student_detail'

   resources :courses, shallow: true  do
     resources :concepts, shallow: true  do
       resources :concept_resources
       resources :concept_prerequisites
       resources :assessments
     end
   end

   resources :preferences
   resources :learned_courses
   resources :learned_concepts
   resources :questions

  resources :students
  resources :questions
  resources :question_answers
  resources :choices
  resources :assessment_infos
end

app/models/assessment.rb
class Assessment < ApplicationRecord
    enum level:{
        beginner: 1,
        intermediate: 2,
        advanced: 3
    }
    has_many :questions
    belongs_to :concept
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]

  # GET /assessments
  # GET /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1
  # GET /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
    @assessment.concept_id = params[:concept_id]
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments
  # POST /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to edit_concept_url(@assessment.concept_id), notice: 'Assessment was successfully created.' }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1
  # PATCH/PUT /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to edit_concept_url(@assessment.concept_id), notice: 'Assessment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1
  # DELETE /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to edit_concept_url(@assessment.concept_id), notice: 'Assessment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assessment_params
      params.require(:assessment).permit(:title, :level, :min_passing_grade, :concept_id)
    end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_assessment.html.erb
      <tr>
        <td><%= assessment.level%></td>
        <td><%= assessment.min_passing_grade %></td>
        <td><%= assessment.questions.count %></td>
      

        <td>
          <%= link_to 'Edit', edit_assessment_path(assessment), class: 'btn btn-primary' %>
          <%= link_to 'Remove', assessment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>

app/views/assessments/_form.html.erb
  <% if assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :concept_id %>
    <%= f.number_field :concept_id , class: 'hidden'%>
    <span class="label label-info"><%= Concept.find(assessment.concept_id)&.title  %></span>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title , :class=> 'form-control '%>
  </div>
  <div class="form-group">
    <%= f.label :level %>
    <%= f.collection_select :level, Assessment.levels, :first, :first, {:include_blank => '-- Select --'},{:class => 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :min_passing_grade %>
    <%= f.text_field :min_passing_grade , class: "form-control"%>
  </div>

app/views/assessments/edit.html.erb
<h1>Editing Assessment</h1>



<%= form_for @assessment, html: { multipart: true } do |f| %>
    <%= render 'form', f: f, :assessment => @assessment %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', edit_concept_path(@assessment.concept_id) %>

app/views/assessments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assessments</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Min passing grade</th>
      <th>Concept</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assessments.each do |assessment| %>
      <tr>
        <td><%= assessment.level %></td>
        <td><%= assessment.min_passing_grade %></td>
        <td><%= assessment.concept_id %></td>
        <td><%= link_to 'Show', assessment %></td>
        <td><%= link_to 'Edit', edit_assessment_path(assessment) %></td>
        <td><%= link_to 'Destroy', assessment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assessment', new_assessment_path %>

app/views/assessments/new.html.erb
<h1>New Assessment</h1>

<%= form_for @assessment,url:concept_assessments_path, html: { multipart: true } do |f| %>
    <%= render 'form', f: f, :assessment => @assessment %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', edit_concept_path(@assessment.concept_id) %>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Level:</strong>
  <%= @assessment.title %>
</p>
<p>
  <strong>Level:</strong>
  <%= @assessment.level %>
</p>

<p>
  <strong>Min passing grade:</strong>
  <%= @assessment.min_passing_grade %>
</p>

<p>
  <strong>Concept:</strong>
  <%= Concept.find(@assessment.concept_id).title %>
</p>

<div class="x_panel">
  <div class="x_title">
    <h2>Questions</h2>
    <%= link_to 'Add Question' , new_question_path(assessment_id: params[:id]) , class: 'btn btn-primary pull-right'%>
    <div class="clearfix"></div>
  </div>
  <div>
      <table class="table table-hover">
          <thead>
              <tr>
                  <th>Question</th>
                  <th>Question Type</th>
                  <th>Difficuty Level</th>
                  <th>Average Time(in Mins)</th>
                  <th colspan="3">Actions</th>
              </tr>
          </thead>
          <tbody>
              <%= render @assessment.questions, questions:@assessment.questions %>
          </tbody>
      </table>
  </div>

  <div>


<%= link_to 'Edit', edit_assessment_path(@assessment) %> |
<%= link_to 'Back', edit_concept_path(@assessment.concept_id) %>