config/routes.rb
Rails.application.routes.draw do
  resources :concepts
  devise_for :teachers
  devise_for :students, :controllers => { :registrations => "registrations" }
  devise_for :users

   root 'courses#index'
   put 'courses/:id/register', to: 'courses#register'
   get '/learned_courses/:lc_id/concepts/:id/learn', to: 'concepts#learn'
   get '/courses/:id/students', to: 'courses#students'
   get 'courses/:course_id/students/:id', to: 'courses#student_detail'

   resources :courses, shallow: true  do
     resources :concepts, shallow: true  do
       resources :concept_resources
       resources :concept_prerequisites
       resources :assessments
     end
   end

   resources :preferences
   resources :learned_courses
   resources :learned_concepts
   resources :questions

  resources :students
  resources :questions
  resources :question_answers
  resources :choices
  resources :assessment_infos
end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
    @choice.question_id = params[:question_id]
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)
    respond_to do |format|
      if @choice.save
        format.html { redirect_to question_path(@choice.question_id), notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to question_path(@choice.question_id), notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    question_id = @choice.question_id

    @choice.destroy
    respond_to do |format|
      format.html { redirect_to   question_path(question_id), notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:letter, :content, :question_id)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_choice.html.erb
<tr>
  <td><%= choice.letter %></td>
  <td><%= choice.content %></td>

  <td>
    <%= link_to 'Remove', choice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/choices/_form.html.erb
<%= form_for(choice) do |f| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :letter %>
    <%= f.text_field :letter %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <%= f.number_field :question_id, :hidden => true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th>Letter</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.letter %></td>
        <td><%= choice.content %></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', question_path(@choice.question_id)%>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Letter:</strong>
  <%= @choice.letter %>
</p>

<p>
  <strong>Content:</strong>
  <%= @choice.content %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>