config/routes.rb
Rails.application.routes.draw do
  resources :concepts
  devise_for :teachers
  devise_for :students, :controllers => { :registrations => "registrations" }
  devise_for :users

   root 'courses#index'
   put 'courses/:id/register', to: 'courses#register'
   get '/learned_courses/:lc_id/concepts/:id/learn', to: 'concepts#learn'
   get '/courses/:id/students', to: 'courses#students'
   get 'courses/:course_id/students/:id', to: 'courses#student_detail'

   resources :courses, shallow: true  do
     resources :concepts, shallow: true  do
       resources :concept_resources
       resources :concept_prerequisites
       resources :assessments
     end
   end

   resources :preferences
   resources :learned_courses
   resources :learned_concepts
   resources :questions

  resources :students
  resources :questions
  resources :question_answers
  resources :choices
  resources :assessment_infos
end

app/models/concept.rb
# == Schema Information
#
# Table name: concepts
#
#  id        :integer          not null, primary key
#  level     :integer          not null
#  title     :string
#  course_id :integer
#

# create_table :concepts do |t|
#   t.integer  :level , null: false
#   t.string   :title
#   t.string   :course_id

class Concept < ApplicationRecord
  has_many :concept_resources  
  belongs_to :course
  has_many :concept_prerequisites,
    class_name: "ConceptPrerequisite", 
    foreign_key: "concept_id"
  has_many :prerequisites, :through => :concept_prerequisites 
  has_many :assessments
 
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]

  # GET /concepts
  # GET /concepts.json
  def index
    @concepts = Concept.all
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
    @concept.course_id = params[:course_id];
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)
    if(@concept.prerequisites.nil? || @concept.prerequisites.size == 0)
      @concept.level = 1
    else
      @concept.level =  @concept.prerequisites.max_by(&:level).level+1
    end
    @concept.course_id = params[:course_id]
    @course = Course.find(@concept.course_id)

    respond_to do |format|
      if @concept.save
        format.html { redirect_to  edit_course_path(@course), notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location:  @course }
      else
        format.html { render :new }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    @course = Course.find(@concept.course_id)
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to edit_course_path(@course), notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @course = Course.find(@concept.course_id)
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to edit_course_path(@course), notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def learn
    logger.debug("**********learn************")
   @learned_concept= LearnedConcept.new
   @concept=Concept.find(params[:id])
    learner_pref=LearnerPreference.where(:student_id=>current_user.id).first
    if learner_pref.nil?
      redirect_to new_preference_path
    else
      preference=Preference.find(learner_pref.preference_id)

      @learned_concept.learned_course_id=params[:lc_id]
      @learned_concept.start_time= Time.now
      @learned_concept.concept_id=@concept.id

      logger.debug("---preference---pm-#{preference.presentation_mode}")
      logger.debug("---preference---rt-#{preference.resource_type}")

      @concept_resource=@concept.concept_resources.select{
          |cr| cr.presentation_mode == preference.presentation_mode &&
            cr.resource_type == preference.resource_type
      }.first


      if(@concept_resource.nil?)
        @learned_course=LearnedCourse.find(@learned_concept.learned_course_id)

        respond_to do |format|
          format.html { redirect_to learned_course_path(@learned_course), notice: 'resource not found' }
          format.json { head :no_content }
        end
      else
        @learned_concept.resource_id=@concept_resource.id
      end

    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_concept
    @concept = Concept.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def concept_params
    params.require(:concept).permit(:level, :title, :course_id, prerequisite_ids:[])
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_concept.html.erb
<tr>
        <td><%= concept.title %></td>
        <td><%= concept.level %></td>      
        <td>
          <%= link_to 'Edit', edit_concept_path(concept) %> |
          <%= link_to 'Delete', concept, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
<br>

app/views/concepts/_form.html.erb
<div class="x_panel">
  <div>
    <%= form_for @concept do |f| %>
              <% if @concept.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

                    <ul>
                        <% @concept.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
              <% end %>
              <div class="field">
                  <%= f.label :title %><br>
                  <%= f.text_field :title %>
              </div>
              <div class="field">
                  <%= f.label :level %><br>
                  <%= f.number_field :level, :disabled=> true, :class=>'form-control' %>
              </div>
              <div class="field">
                  <%= f.label :course_id %><br>
                  <%= Course.find(@concept.course_id).title %>
              </div>
              <br>
              <div class="field">
                <div class = "col-md-3">
                    <%= f.label "Prerequisites" %>
                </div>

                  <div class= "col-md-9">
                   <%= f.collection_check_boxes :prerequisite_ids,Concept.where.not(id: @concept.id), :id, :title do |con| %>
                    <div class="col-md-3">
                        <%= con.check_box %>
                        <%= con.label %>
                    </div>
                  <% end %>
                </div>
              </div>
              <br>
              <div class="actions ">
                  <%= f.submit :class => 'btn btn-primary' %>
              </div>
              <br>
    <% end %>
  </div>
</div>

app/views/concepts/edit.html.erb
<h1>Editing Concept</h1>
<div class="x_panel">
  <div class="col-sm-4">
    <h2>Edit Concept</h2>
  </div>
  <div class="col-sm-8">
      <%= link_to 'Cancel', edit_course_path(@concept.course_id),  :class => "btn btn-default pull-right  "%>
  </div>
  
  <%= render 'form' %>
</div>

<div class="x_panel">
    <div class="x_title">
        <div class="col-md-8">
         <h2>Resources for Concept</h2>
        </div>
        <div class="col-md-4">
           <%= link_to 'Add New Resource', new_concept_concept_resource_path(@concept),:class=>'btn btn-primary' %>
        </div>
        <div class="clearfix"></div>
    </div>

    <div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>File name</th>
                    <th>Format</th>
                    <th>Presentation mode</th>
                    <th>Resource type</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            <tbody>
                <%= render @concept.concept_resources, concept_resources:@concept.concept_resources %>
            </tbody>
        </table>
    </div>
</div>

<div class="x_panel">
    <div class="x_title">
        <div class="col-md-8">
         <h2>Assessments for Concept</h2>
        </div>
        <div class="col-md-4">
           <%= link_to 'Add New Assessment', new_concept_assessment_path(@concept),:class=>'btn btn-primary' %>
        </div>
        <div class="clearfix"></div>
    </div>

    <div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Level</th>
                    <th>Passing Grade</th>
                    <th>No.of Questions</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            <tbody>
                <%= render @concept.assessments, assessments:@concept.assessments %>
            </tbody>
        </table>
    </div>
</div>



<%= link_to 'Show', @concept %> |
<%= link_to 'Back', course_concepts_path(@concept.course) %>

app/views/concepts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Concepts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Level</th>
      <th>Title</th>
      <th>Course</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= concept.level %></td>
        <td><%= concept.title %></td>
        <td><%= concept.course.title %></td>
        <td><%= link_to 'Show', concept %> |
          <%= link_to 'Edit', edit_concept_path(concept) %> |
          <%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept',  new_course_concept_path %>

app/views/concepts/learn.html.erb
<%= form_for @learned_concept, url:learned_concepts_path do |f| %>

 <% if @learned_concept.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@learned_concept.errors.count, "error") %> occured:</h2>

        <ul>
            <% @concept.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>

<div class="row hidden">
    <%= f.number_field :learned_course_id %>

      <%= f.number_field :concept_id %>
      <%= f.number_field :resource_id %>
       <%= f.text_field :start_time %>
       <%= f.text_field :end_time %>
       <%= f.text_field :completed ,:value=>false%>
</div>
  <div class="row">
    <% cr = ConceptResource.find(@learned_concept.resource_id) %>
    <% if  cr.resource_content_type == "application/pdf" %>

         <iframe src="/pdfjs/web/viewer.html?file=<%=cr.resource.url%>" style="border: 0" width="70%" height="600" frameborder="0" scrolling="no"></iframe>

    <% elsif cr.resource_content_type == "video/mp4" %>
        <%=  video_tag("#{cr.resource.url}",  size: "700x500",controls: true, autobuffer: true) %>
     <% end %>

  </div>

  <%=  f.submit 'Continue >>', :class=>'btn btn-primary'%>

<%end%>
<%= link_to 'Back' %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>

<%= form_for @concept, url:course_concepts_path do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

        <ul>
            <% @concept.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
  </div>
  <div class="field">
      <%= f.fields_for @concept.course do |c| %>
        <%= c.label :course_id %><br>
        <%= c.text_field :title, :disabled=>true%>
      <%end%>
  </div>
  <div class="field">
      <%= f.label "Prerequisites" %><br />
      <%= f.collection_check_boxes :prerequisite_ids, Concept.where(course_id:@concept.course_id), :id, :title do |con| %>
        <div class="collection-check-box">
            <%= con.check_box %>
            <%= con.label %>
        </div>
      <% end %>
  </div>
  <br>
  <div class="actions">
      <br>
      <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', :back %>

app/views/concepts/show.html.erb
<div class="row">
    <p id="notice"><%= notice %></p>

    <p>
        <strong>Level:</strong>
        <%= @concept.level %>
    </p>

    <p>
        <strong>Title:</strong>
        <%= @concept.title %>
    </p>

    <p>
        <strong>Course:</strong>
        <%= Course.find(@concept.course_id).title %>
    </p>

    <p>
      <strong>Prerequisites</strong>
      <ul>
          <% @concept.prerequisites.each do |pq| %>
            <li>(<%= Concept.find(pq.id).id %>) <%= Concept.find(pq.id). title%></li>
          <% end %>
       <ul>
     </p>
</div>


<%= link_to 'Edit', edit_concept_path(@concept) %> 
<%= link_to 'Back', course_concepts_path(@concept.course) %>