config/routes.rb
Rails.application.routes.draw do
  resources :concepts
  devise_for :teachers
  devise_for :students, :controllers => { :registrations => "registrations" }
  devise_for :users

   root 'courses#index'
   put 'courses/:id/register', to: 'courses#register'
   get '/learned_courses/:lc_id/concepts/:id/learn', to: 'concepts#learn'
   get '/courses/:id/students', to: 'courses#students'
   get 'courses/:course_id/students/:id', to: 'courses#student_detail'

   resources :courses, shallow: true  do
     resources :concepts, shallow: true  do
       resources :concept_resources
       resources :concept_prerequisites
       resources :assessments
     end
   end

   resources :preferences
   resources :learned_courses
   resources :learned_concepts
   resources :questions

  resources :students
  resources :questions
  resources :question_answers
  resources :choices
  resources :assessment_infos
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register
    @course=Course.find(params[:id])

    if(LearnedCourse.where(course_id: @course.id, student_id: current_user.id ).empty?)
      @learned_course = LearnedCourse.create do |lc|
        lc.student_id = current_user.id
        lc.course_id = @course.id
        lc.completion_level = 0
      end
      respond_to do |format|
        format.html { redirect_to course_path(@course), notice: 'Registered for the course.' }
        format.json { head :no_content }
      end
    else
      @learned_course = LearnedCourse.where(course_id: @course.id, student_id: current_user.id ).first
      redirect_to learned_course_path(), warning: 'Already registered for the course.'
    end
  end

  def students
    course_id = params[:id]
    @students = Student.where(:id => LearnedCourse.where(course_id: course_id).pluck(:student_id) )
    @students
  end

  def student_detail
    course_id = params[:course_id]
    student_id = params[:id]

    @student = Student.find(student_id)
    @learned_course = LearnedCourse.where({course_id: course_id, student_id: student_id})

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:allowed_time_gap, :description, :end_date, :passing_grade, :start_date, :title)
    end
end

app/views/courses/_form.html.erb
<div class="x_panel">
    <div>
      <%= form_for(course) do |f| %>
        <% if course.errors.any? %>
          <div class="panel panel-danger">
            <div class="panel-heading">
              <%= pluralize(course.errors.count, "error") %> prohibited this course from being saved.
            </div>

            <div class="panel-body">
              <ul>
                <% course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :start_date %>
            <%= f.datetime_select :start_date, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :end_date %>
            <%= f.datetime_select :end_date, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :passing_grade %>
            <%= f.text_field :passing_grade, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :allowed_time_gap %>
            <%= f.text_field :allowed_time_gap, :class => 'form-control' %>
          </div>

      <div class="actions">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
  <% end %>

    </div>
  </div>

app/views/courses/edit.html.erb
<div class="x_panel">
  <div class="col-sm-4">
    <h2>Edit Course</h2>
  </div>
  <div class="col-sm-8">
      <%= link_to 'Cancel', courses_path,  :class => "btn btn-default pull-right  "%>
  </div>
  <%= render 'form', course: @course %>
</div>

<div class="x_panel">
  <div class="x_title">
    <div class="col-md-8">
      <h2>Concepts in Course</h2>
    </div>
    <div class="clearfix"></div>
  </div>
  <div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Level</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @course.concepts, concepts:@course.concepts %>
      </tbody>
    </table>
  </div>
</div>


<%= link_to 'Add New Concept', new_course_concept_path(@course), :class=>'btn btn-primary' %>

app/views/courses/index.html.erb
<!-- page content -->

<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Courses Home</h3>

    </div>

    <div class="title_right">
      <div class="col-md-8 col-sm-8 col-xs-12 form-inline pull-right top_search">
        <% if current_user.type == 'Teacher'%>
          <div class="input-group">
            <a href="<%=new_course_path%>" class="btn btn-primary"><i class="fa fa-plus"></i> New Course </a>
          </div>
        <%end%>
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>

        </div>


      </div>
    </div>
    <div class="clearfix"></div>
    <% @courses.each do |course| %>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2><%= course.title %></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <div class="col-md-12 col-sm-12 col-xs-12" style="border:0px solid #e5e5e5;">
                  <p><%= course.description %></p>

                  <div class="">
                    <h2>Course Dates</h2>
                    <small><%= course.start_date %> - <%= course.end_date %></small>
                  </div>

                  <div class="">
                    <h2>Passing grade</h2>
                    <small><%= course.passing_grade %></small>
                  </div>
                  <br>

                  <div class="">
                    <% if current_user.type=='Student'%>
                        <% if Student.find(current_user.id).learned_courses.find_by(course_id: course.id) %>
                            <a href="<%= learned_course_path(Student.find(current_user.id).learned_courses.find_by(course_id: course.id))%>" class="btn btn-primary">Go to Course</a>

                        <% else %>
                            <%= link_to 'Register', "courses/#{course.id}/register", method: :put, :class => 'btn btn-primary' %>
                        <% end %>
                    <% end %>
                    <% if current_user.type == 'Teacher' %>
                        <%= link_to 'View students',"/courses/#{course.id}/students", :class => "btn btn-primary" %>
                        <%= link_to 'Edit', edit_course_path(course), :class => "btn btn-primary" %>
                        <%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>

                    <% end %>
                  </div>
                  <br>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>

  </div>
</div>

<!-- /page content -->

app/views/courses/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>New Course</h2>
    <ol class="breadcrumb">
      <li>
        <a href="#">Course</a>
      </li>
      <li class="active">
        <strong>New</strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-8">
    <div class="title-action">
      <%= link_to 'Cancel', courses_path,  :class => "btn btn-default"%>
    </div>
  </div>
</div>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
    <p>
      <strong>Allowed time gap:</strong>
      <%= @course.allowed_time_gap %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @course.description %>
    </p>

    <p>
      <strong>End date:</strong>
      <%= @course.end_date %>
    </p>

    <p>
      <strong>Passing grade:</strong>
      <%= @course.passing_grade %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @course.start_date %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @course.title %>
    </p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/students.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Students</h2>

        <div class="clearfix"></div>
      </div>
      <div class="x_content">

        <!-- start project list -->
        <table class="table table-striped projects">
          <thead>
          <tr>
            <th style="width: 1%">#</th>
            <th style="width: 20%">Student Name</th>
            <th>Progress</th>
            <th>Current Grade</th>
            <th style="width: 20%"></th>
          </tr>
          </thead>
          <tbody>
         <% @students.each do |student| %>
          <% lc= student.learned_courses.find_by(course_id: params[:id]) %>
          <tr>
            <td>#</td>
            <td>
              <a><%= student.name %></a>
            </td>
            <td class="project_progress">
              <div class="progress progress_sm">
                <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="57" style="width: <%= lc.completion_level*100%>%;" aria-valuenow="56"></div>
              </div>
              <small><%= sprintf "%.2f", lc.completion_level*100%>% Complete</small>
            </td>
            <td>
                <%= sprintf "%.2f", lc.current_grade%>
            </td>
            <td>
              <a href="/courses/<%=params[:id]%>/students/<%=student.id%>" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>

            </td>
          </tr>
         <% end %>

          </tbody>
        </table>
        <!-- end project list -->

      </div>
    </div>
  </div>
</div>